* Research Proposal
- 1300
- 15% 13% 15% 43% 12%

** Aims & Objectives
- 171

What are the overall aims of the work? What objectives are
necessary to meet the aims?

What are you trying to achieve with your research? What is the
purpose? As discussed earlier, this comes back to the original
reason why you're applying for a research degree. Are you
addressing a gap in the current research? Do you want to look at
a theory more closely and test it out? Is there something you're
trying to prove or disprove? To help you clarify this, think
about the potential outcome of your research if you were
successful – that is your aim. Make sure that this is a clearly
focused statement.

Your objectives will be your aim broken down – the steps to
achieving the intended outcome. They are the smaller proof points
that will underpin your research's purpose. Be logical in the
order of how you present these so that each succeeds the previous
– ie, if you need to achieve 'a' before 'b' before 'c', then make
sure you order your objectives a, b, c.

** Synopsis ~= Abstract
- 199

key aspects will be investigating

The synopsis is a brief but clear summary of what your research
is about and outlines the key aspects of what you will
investigate as well as the expected outcomes. It briefly covers
the what, why and how of your research. A good way to evaluate if
you have written a strong synopsis is to get somebody to read it
without reading the rest of your research proposal. Would they
know what your research is about?

** Background
Brief review of literature in the area of interest. Describe what
research lays the groundwork for your topic.

Now that you have your question clarified, it is time to explain
the why. Why are you choosing to research problem 'x' or issue
'y'? Here you need to demonstrate an understanding of the current
research climate for your area of interest.

Providing context for your research topic through a literature
review shows the assessor that you understand what is currently
being discussed about your topic and what has already been
published. Demonstrate you have a strong understanding of the key
topics, important studies, notable researchers etc in your area
of research and how these have contributed to the current
landscape.

** Expected Research Contribution
- 155

Why is the topic/creative work important? Describe how the
research may be novel and its impact on the discipline.

Why is your research question or hypothesis worth asking? How is
the current research lacking or falling short? What impact will
your research have on the discipline? Will you be extending an
area of knowledge, applying it to new contexts, solving a
problem, testing a theory, or challenging an existing one?
Establish why your research is important by convincing your
audience there is a gap.

Your research proposal is your own statement of originality. What
will be the outcome of your research contribution? Your research
proposal should demonstrate both your current level of knowledge
and how the pursuit of your question or hypothesis will create a
new understanding and generate new information. Show how your
research is innovative and original.

Be sure to draw links between your research and the
faculty/school you're applying to. Why have you chosen your
supervisor to guide you with your thesis? What research have they
or their school done to reinforce and support your own work? Cite
these reasons to demonstrate how your research will benefit and
contribute to the current body of knowledge.

** Proposed Methodology
- 560

Approach or methodology to be used in the research, the
materials/equipment you intend to use, your
space/laboratory/studio requirements.

Provide an overview of the methodology and techniques you will
use to conduct your research. Which materials and equipment you
will use? Which theoretical frameworks will you draw on? Which
method will you use to collect data?

Highlight why you have chosen this particular methodology,
detailing its own merits, but also why others may not have been
as suitable. You need to demonstrate that you have put thought
into your approach and why it's the most appropriate way to carry
out your research. It should also highlight potential limitations
you anticipate facing, feasibility within time and other
constraints, ethical considerations and how you will address
these, and general resources etc.

** Work Plan & Resources
- 203

A work plan is a critical component of your research proposal
because it indicates the feasibility of completion within the
timeframe and supports you in achieving your objectives over the
course of your degree.

Consider the milestones you aim to achieve at each stage of your
research. A PhD or master's degree by research can take two to
four years of full-time study to complete. It might be helpful to
offer year one in detail and the following years in broader
terms. Ultimately you have to show that your research is likely
to be both original and finished – and that you understand the
time involved.

** References
